#Makefile one level down from top of application tree
TOP = ..
include $(TOP)/configure/CONFIG

#directories in which to build
DIRS += simple
DIRS += johng
DIRS += validate
DIRS += demo
DIRS += race
DIRS += unit

include $(TOP)/configure/RULES_DIRS
