TOP = ../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

# Products
PROD += 

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

