TOP = ../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

PROD_HOST += pvGetAsync
PROD_LIBS += Com ca

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
