#!/bin/sh 
#
# sncVersion - create the snc version module
#

VERSION=$1
DATE=`date`
echo	'/* sncVersion.c - version & date */'
echo	'/* Created by sncVersion */'
echo	'char *sncVersion = "@(#)SNC Version '${VERSION}': '${DATE}'";'
