TOP = ../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#  Location of SNL compiler
SNC = $(INSTALL_HOST_BIN)/snc

#  Generate snc main program
SNCFLAGS = +m

#  Products
PROD_HOST = control

#  Libraries
PROD_LIBS += seq

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
