#==============================================================
#
#  Abs:  Make file for IOC Components
#      
#  Name: Makefile.Vx 
#
#  Facility:  SLAC/PEP-II 
#
#  Auth: dd-mmm-yyyy, Author's Name  (USERNAME)
#  Rev:  dd-mmm-yyyy, First Lastname (USERNAME)
#
#--------------------------------------------------------------
#  Mod:
#==============================================================
#
# default definition for local epics directory
TOP = ../../..
include $(TOP)/config/CONFIG_APP
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#
#INC += xxx.h

USR_CFLAGS   += -O0

# Needed for sequences
USR_CPPFLAGS += -I $(EPICS_BASE)/include

# Sequences 
SRCS.c += ../sncEntry.st ../sncDelay.st ../sncOptt.st ../sncOpttVar.st ../sncEntryOpte.st ../sncExitOptx.st ../sncEntryVar.st

# Sequences Objects
OBJS += sncEntry.o sncDelay.o sncOptt.o sncOpttVar.o sncEntryOpte.o sncExitOptx.o sncEntryVar.o

# Install objects and executables
PROD += sncEntry.o sncDelay.o sncOptt.o sncOpttVar.o sncEntryOpte.o sncExitOptx.o sncEntryVar.o

include $(TOP)/config/RULES.Vx
#
#----------------------------------------
#  ADD RULES AFTER THIS LINE




