TOP = ..
include $(TOP)/configure/CONFIG

DIRS += cmdButtons
DIRS += demo
DIRS += johng
#DIRS += parallel
DIRS += simple
DIRS += small
DIRS += pvGetAsync
DIRS += traffic

include $(TOP)/configure/RULES_DIRS
