TOP = ../../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

SNC = $(INSTALL_HOST_BIN)/snc

OBJS_IOC += control.st
OBJS_IOC += demo.st
OBJS_IOC += johng.st
OBJS_IOC += local.st
#OBJS_IOC += misplacedExit.st
OBJS_IOC += sncDelay.st
OBJS_IOC += sncEntry.st
OBJS_IOC += sncEntryOpte.st
OBJS_IOC += sncEntryVar.st
OBJS_IOC += sncExEntry.st
OBJS_IOC += sncExOpt.st
OBJS_IOC += sncExOpt_DuplOpt.st
OBJS_IOC += sncExOpt_UnrecOpt.st
OBJS_IOC += sncExample.st
OBJS_IOC += sncExitOptx.st
OBJS_IOC += sncOptt.st
OBJS_IOC += sncOpttVar.st
#OBJS_IOC += tcsSeq.st

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
