TOP = ../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

TESTSCRIPTS_HOST += test.t

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
