#==============================================================
#
#  Abs:  Make file for IOC Components
#      
#  Name: Makefile.Vx 
#
#  Facility:  SLAC/PEP-II 
#
#  Auth: dd-mmm-yyyy, Author's Name  (USERNAME)
#  Rev:  dd-mmm-yyyy, First Lastname (USERNAME)
#
#--------------------------------------------------------------
#  Mod:
#==============================================================
#
# default definition for local epics directory
TOP = ../../..
include $(TOP)/config/CONFIG_APP
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#
#INC += xxx.h

USR_CFLAGS   += -O0

# Needed for sequences
USR_CPPFLAGS += -I $(EPICS_BASE)/include

# Sequences 
SRCS.c += ../misplacedExit.st sncExOpt_DuplOpt.st

# Sequences Objects
OBJS += misplacedExit.o sncExOpt_DuplOpt.o

# Install objects and executables
PROD += misplacedExit.o sncExOpt_DuplOpt.o

include $(TOP)/config/RULES.Vx
#
#----------------------------------------
#  ADD RULES AFTER THIS LINE




